apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: boutique
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/boutique-orders:latest
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3005"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL
