apiVersion: v1
kind: Service
metadata:
  name: boutique-postgres
  namespace: boutique
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None   # Headless service for StatefulSet
  selector:
    app: postgres
