resources:
  - namespace.yaml
  - secrets.yaml
  - postgres/init-scripts-configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - backend/gateway.yaml
  - backend/auth.yaml
  - backend/product-service.yaml
  - backend/order-service.yaml
  - backend/orders.yaml
  - backend/user-service.yaml
  - frontend/deployment.yaml
