resources:
  - namespace.yaml
  - secrets.yaml
  - k8s/database/init-scripts-configmap.yaml
  - k8s/database/statefulset.yaml
  - k8s/database/service.yaml
  - k8s/backend/gateway.yaml
  - k8s/backend/auth.yaml
  - k8s/backend/product-service.yaml
  - k8s/backend/order-service.yaml
  - k8s/backend/orders.yaml
  - k8s/backend/user-service.yaml
  - k8s/frontend/deployment.yaml
