name: Boutique CI Pipeline

on:
  push:
    branches:
      - project-demo

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - auth
          - gateway
          - orders
          - order-service
          - product-service
          - user-service
          - frontend
          - database

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
     
      - name: Build Docker Image
        run: |
          if [ "${{ matrix.service }}" == "frontend" ]; then
            BUILD_PATH="projects/boutique-microservices/frontend"

          elif [ "${{ matrix.service }}" == "database" ]; then
            BUILD_PATH="projects/boutique-microservices/database"
          else
            BUILD_PATH="projects/boutique-microservices/backend/services/${{ matrix.service }}"
          fi

          echo "Building from $BUILD_PATH"

          docker build \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/${{ matrix.service }}:$IMAGE_TAG \
          $BUILD_PATH


      - name: Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ matrix.service }}:${{ github.sha }}
          echo "Pushing $IMAGE_URI"
          docker push $IMAGE_URI

